[package]
name = "ragent_core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A framework for building LLM agents."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
documented = "0.1.2"
bevy = { version = "0.13.0", default-features = false }